### ISSUE TITLE
Blank White Instagram Widget

### ISSUE THREAD

**Issue by ghost** [supermamon/scriptable-scripts#2]
Instagram widget now displays as a blank white space. This is happening in v1.1 and v1.3 on an iPhone 8 Plus running iOS 14.2.

Edit to add: it is now displaying an error message that says, “The data couldn’t be read because it isn’t in the correct format.”

**Comment by giuliomagnifico** [comment]
Same here, sometimes the widget is blank/white without. After some times, it starts working again.

**Comment by supermamon** [comment]
One reason that may be causing this is that rate-limiting has been applied to Instagram's public API. Two thing that I found might help are (1) change the REFRESH_INTERVAL variable to a higher value. I'll probably remove that on the next version since it's not really helping to refresh the widget. And (2) toggling between Wifi & Cellular sometimes helps. 

Besides those 2 options, I don't really have a way force Instagram's API to overcome the limits.

**Comment by cbuffalino** [comment]
I found that running NordVPN on iPhone 12 pro would cause the widget to not function while on either WiFi, LTE or 5G. Turning it off instantly returned functionality.

**Comment by giuliomagnifico** [comment]
> I found that running NordVPN on iPhone 12 pro would cause the widget to not function while on either WiFi, LTE or 5G. Turning it off instantly returned functionality. 

Probably because you change the IP (or something else that identify you) and IG "gives" you another queries. Not a solution but good to know.
